### ISSUE TITLE
Esmecata x eggnog singularity error

### ISSUE THREAD

**Issue by rssco** [AuReMe/esmecata#15]
Hi, 

We would like to implement eggnog in the singularity of Esmecata, but we (@lecorguille) met an error: 

INFO:    underlay of /etc/localtime required more than 50 (82) bind mounts
Traceback (most recent call last):
  File "/opt/conda/lib/python3.12/urllib/request.py", line 1344, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/conda/lib/python3.12/http/client.py", line 1331, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/conda/lib/python3.12/http/client.py", line 1377, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.12/http/client.py", line 1326, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.12/http/client.py", line 1085, in _send_output
    self.send(msg)
  File "/opt/conda/lib/python3.12/http/client.py", line 1029, in send
    self.connect()
  File "/opt/conda/lib/python3.12/http/client.py", line 1472, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/ssl.py", line 1042, in _create
    self.do_handshake()
  File "/opt/conda/lib/python3.12/ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/esmecata", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/esmecata/__main__.py", line 433, in main
    perform_workflow_eggnog(args.input, args.output, args.eggnog_database, busco_score,
  File "/opt/conda/lib/python3.12/site-packages/esmecata/workflow.py", line 203, in perform_workflow_eggnog
    retrieve_proteomes(input_file, proteomes_output_folder, busco_percentage_keep,
  File "/opt/conda/lib/python3.12/site-packages/esmecata/proteomes.py", line 1409, in retrieve_proteomes
    uniprot_releases = get_rest_uniprot_release(options)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/esmecata/utils.py", line 167, in get_rest_uniprot_release
    uniprot_response = urllib_query(uniprot_urllib_request)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/esmecata/utils.py", line 142, in urllib_query
    response = urllib.request.urlopen(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/urllib/request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/urllib/request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/urllib/request.py", line 1392, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/urllib/request.py", line 1347, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>

It seems that esmecata in the eggnog workflow attempts to access the Uniprot REST API (uniprot_releases = get_rest_uniprot_release(options).

Could you help us ? :) 

Thank you for your help, 
Coralie

**Comment by ArnaudBelcour** [comment]
Hi @rssco,

The fact that esmecata workflow with eggnog attempts a connection with UniProt REST API is expected for several things (1) searching for proteomes associated with your taxon, (2) downloading them and (3) downloading metadata of the UniProt release.

This error comes from UniProt blocking the query while esmecata has already downloaded the proteomes and is trying to retrieve metadata on UniProt.
Sometimes UnIProt blocks the query due to the traffic, can you retry again and see if it leads to the same error?

Best regards,
Arnaud Belcour.
